version: '3.8'

services:
  mongodb:
    image: mongo:6
    container_name: mongo_db
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin123

  backend:
    build: ./backend
    container_name: backend_api
    restart: unless-stopped
    ports:
      - "5000:5000"
    environment:
      - MONGO_URL=mongodb://admin:admin123@mongodb:27017/deliverydb?authSource=admin
      - PORT=5000
    volumes:
      - ./backend:/app
    depends_on:
      - mongodb

  frontend:
    build: ./frontend
    container_name: frontend_app
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
    depends_on:
      - backend

volumes:
  mongo_data:

